// lines.js — every spoken line. Recorded to audio/<id>.mp3 by scripts/voice-gen.mjs (Tyler, the Turbo TJ announcer).
// If an mp3 is missing, the app falls back to the tablet's built-in voice.
export const LINES = {
  start: "Let's suit up, hero!",
  t_masks: 'Masks!',
  t_powers: 'Powers!',
  t_gear: 'Hero gear!',
  t_looks: 'Cool looks!',
  m_eye: 'Hero mask!',
  m_robot: 'Robot helmet!',
  m_thunder: 'Thunder helmet!',
  m_dino: 'Dino hood! Roar!',
  m_ninja: 'Ninja mask!',
  m_astro: 'Astronaut helmet!',
  m_lion: 'Lion hero!',
  m_knight: 'Knight helmet!',
  m_race: 'Race helmet! Vroom vroom!',
  m_dragon: 'Dragon horns! Roar!',
  m_viking: 'Viking helmet!',
  m_crown: 'Hero crown! You are the king!',
  m_mech: 'Mech pilot helmet!',
  m_samurai: 'Samurai helmet!',
  m_diver: 'Deep sea diver!',
  m_fireman: 'Fire chief helmet!',
  p_fire: 'Fire breath! Open your mouth!',
  p_ice: 'Ice breath! Open your mouth!',
  p_laser: 'Laser eyes! Make a surprised face!',
  p_bubble: 'Bubble breath! Open your mouth!',
  p_shout: 'Super shout! Open your mouth wide!',
  p_rainbow: 'Rainbow breath! Open your mouth!',
  p_hypno: 'Hypno eyes! Make a surprised face!',
  p_lightning: 'Lightning power! Tap the screen for more!',
  p_shield: 'Power shield! Tap to make it glow!',
  p_speed: 'Super speed! Move fast!',
  p_invisible: 'Invisible! Where did you go?',
  p_aura: 'Power glow!',
  g_cape: 'Super cape!',
  g_badge: 'Your hero badge!',
  g_city: 'Hero City!',
  g_space: 'Outer space!',
  g_wings: 'Hero wings!',
  g_dino: 'Dino Land!',
  g_sky: 'Up in the sky!',
  g_jetpack: 'Jetpack! Blast off!',
  g_robo: 'Robot buddy!',
  g_dinobud: 'Dino buddy!',
  g_underwater: 'Under the sea!',
  g_snow: 'Snowy mountain!',
  g_track: 'Race track!',
  g_hq: 'Hero headquarters!',
  l_comic: 'Comic book!',
  l_cartoon: 'Cartoon!',
  l_pixel: 'Video game!',
  l_night: 'Night vision!',
  l_thermal: 'Heat vision!',
  l_holo: 'Hologram!',
  off: 'All off!',
  tap_hint: 'You can tap the screen to use your power!',
  n3: 'Three!',
  n2: 'Two!',
  n1: 'One!',
  pose: 'Hero pose!',
  saved: 'Awesome! Picture saved!',
  find: "Where's the hero? Look at the screen!",
  dark: "It's too dark! Turn on a light!",
  gallery: 'Your hero pictures!',
  oops: 'Uh oh! Ask a grown-up for help.',
  wait: 'Wait for the camera!',
  toss: 'Throw it away?',
  pick_power: 'Pick a power first!',
};
