// lines.js — every spoken line. Recorded to audio/<id>.mp3 by scripts/voice-gen.mjs (same narrator as TJ's Hero Book).
// If an mp3 is missing, the app falls back to the tablet's built-in voice.
export const LINES = {
  start: "Let's suit up, hero!",
  t_masks: 'Masks!',
  t_powers: 'Powers!',
  t_gear: 'Hero gear!',
  m_eye: 'Hero mask!',
  m_robot: 'Robot helmet!',
  m_thunder: 'Thunder helmet!',
  m_dino: 'Dino hood! Roar!',
  m_ninja: 'Ninja mask!',
  m_astro: 'Astronaut helmet!',
  m_lion: 'Lion hero!',
  m_knight: 'Knight helmet!',
  p_fire: 'Fire breath! Open your mouth!',
  p_ice: 'Ice breath! Open your mouth!',
  p_laser: 'Laser eyes! Make a surprised face!',
  p_bubble: 'Bubble breath! Open your mouth!',
  p_shout: 'Super shout! Open your mouth wide!',
  p_aura: 'Power glow!',
  g_cape: 'Super cape!',
  g_badge: 'Your hero badge!',
  g_city: 'Hero City!',
  g_space: 'Outer space!',
  g_wings: 'Hero wings!',
  g_dino: 'Dino Land!',
  g_sky: 'Up in the sky!',
  off: 'All off!',
  tap_hint: 'You can tap the screen to use your power!',
  n3: 'Three!',
  n2: 'Two!',
  n1: 'One!',
  pose: 'Hero pose!',
  saved: 'Awesome! Picture saved!',
  find: "Where's the hero? Look at the screen!",
  dark: "It's too dark! Turn on a light!",
  gallery: 'Your hero pictures!',
  oops: 'Uh oh! Ask a grown-up for help.',
  wait: 'Wait for the camera!',
  toss: 'Throw it away?',
  pick_power: 'Pick a power first!',
};
